services:
  - type: web
    name: wisdomly-api-qa
    env: node
    branch: dev
    region: oregon
    plan: free
    autoDeploy: true
    healthCheckPath: /health
    buildCommand: pnpm install --frozen-lockfile && pnpm --filter @wisdomly/db db:generate && pnpm --filter @wisdomly/api build
    startCommand: node apps/api/dist/server.js
    envVars:
      - key: NODE_ENV
        value: development
      - key: DATABASE_URL
        sync: false

  - type: web
    name: wisdomly-api-prod
    env: node
    branch: main
    region: oregon
    plan: free
    autoDeploy: true
    healthCheckPath: /health
    buildCommand: pnpm install --frozen-lockfile && pnpm --filter @wisdomly/db db:generate && pnpm --filter @wisdomly/api build
    startCommand: node apps/api/dist/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false