name: Deploy Production

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Deploy API to Render
        run: curl -X POST ${{ secrets.RENDER_PROD_DEPLOY_HOOK }}
